### ISSUE TITLE
Problem with communication

### ISSUE THREAD

**Issue by robustini** [prickle/MavpixelGUI#1]
I've a lot of problems with the Mavpixel GUI, I can't set these parameters (comunication error after the first connection).
The GUI read the led config and then give me an error, i can't see "Mavlink ready" at the bottom.
Same issue with USB and UPD connection.
The Mavlink connection with the Pixhawk work fine, I see the colors changes of the LEDs, I can't adjust the brightness.
I use Arduino Nano, connected with the Mini USB port at 57600 Bd.
Regards,

Marco

![immagine](https://user-images.githubusercontent.com/3864712/32067034-0a296bb8-ba82-11e7-8e60-01c05fd4e2e5.png)

![immagine](https://user-images.githubusercontent.com/3864712/32067046-1052e870-ba82-11e7-9801-e993425ebe9b.png)

**Comment by prickle** [comment]
Hi Marco. Sorry, Mavpixel will not work with an Arduino Nano. This is mainly because of the need for complete control over the mega328's serial pins and the onboard USB to serial converter gets in the way. Also, due to the different bootloader on the Nano there is not enough flash space and manual flashing will result in a truncated binary that will have unpredictable behavior if it works at all. The built-in uploader will not work.

Please give it a try with an Arduino Pro Mini, as described over in the [Mavpixel](https://github.com/prickle/Mavpixel) repository.
